### PR TITLE
Add day-zero page to web-site

### PR DESCRIPTION
**Pull request by ijlyttle**
This is a work-in-progress. FWIW, I am driving the process using the new PR functions in usethis, and so far:

- they are working perfectly.
- I am *really* liking them!

`create_from_github()`:
- forks the repo into my GH account
- clones it to a local directory
- sets up both `origin` and `upstream` remotes
- opens IDE to the new project

`pr_init()`: 
- creates a new branch in my local repository (to avoid the PR-from-master situation)

`pr_push()`: 
- pushes to the `origin` remote for this branch
    - this activates the push/pull arrows in the IDE
- opens a "new PR" page (this one) in my browser
- not usethis-specific, but GitHub now lets us open a draft PR, which I think can be very useful.

### CODE REVIEW

**Comment by ijlyttle** [comment]
Hi @sctyner - this is ready for you to have a first-look-at. At this point, all I want to do is show the formatting, that we have something close to what you might like. Here's a screenshot:

image

To render this yourself, you will need to `install_github("ijlyttle/vembedr")`

If when I build this locally, then serve it, I use the address: http://127.0.0.1:4321/day-zero-prep/

To create a new content page:

```r
blogdown::new_content("title-goes-here.Rmd")
```

Fill in some yaml, then do your R Markdown.

In this case, and in all cases, we would have to add a link in the navbar (I'm putting this here to remind myself).

**Comment by ijlyttle** [comment]
I think at this point, I will just need to make a screencast then make a link in the navbar.

**Comment by sctyner** [comment]
@ijlyttle I'm not familiar with a draft pull request. How would I preview this??

**Comment by ijlyttle** [comment]
Hi @sctyner,

I think the draft is just to make you aware of it. I have requested you as a reviewer now.

I'd be happy to remove the draft status now - I still have to do the screencast and navbar link, perhaps in a follow-up PR.

If you were to accept the PR, you could create your own new content-pages while I get the screencast sorted out.

**Comment by ijlyttle** [comment]
Here's the video, in case you want a preview: https://youtu.be/cKk7rioLFH0 (new link for revised video)

**Comment by sctyner** [comment]
Ok, I will look at this later today and merge in the PR.

**Comment by ijlyttle** [comment]
This *should* be ready to go

**Comment by ijlyttle** [comment]
Now takes into account Amelia's suggestions, using new link to "new" video. 

pull-request [dot] final [dot] final-1

**Comment by sctyner** [comment]
Looks great! How do we want to roll this out to participants? And when?

**Comment by ijlyttle** [comment]
I think we roll it out as soon as we can. I am seeing an issue with the css when I look at the page, I would not mind sorting that out if it does not take too long.

**Comment by ijlyttle** [comment]
Never mind, it was a browser issue. Looks good to me!

I can try to put together some suggested words for you to blast out by email (of course, I would welcome any modifications you might have in mind).

**Comment by ijlyttle** [comment]
First pass at some text:

Hi everyone,

We want to spend as much time as we can at the Unconf working on interesting problems, not installation issues. With that in mind, we want to try an experiment. We propose to make a short activity every week between now and the Unconf, where we demonstrate how you can get your R, RStudio, git, and GitHub ready so we will all be ready to collaborate.

We are pleased to introduce a new section of the Unconf web-site: [day-zero prep](http://uuconf.rbind.io/day-zero-prep/)! Regardless of your plans to attend day-zero, we invite you to participate. As well, if you are already comfortable with your R installation, RStudio, GitHub, etc., you need not do anything to your computer. This is meant to provide guidance only to those who might be looking for guidance.

If you have any questions, you can raise a GitHub issue (part of this week's demonstration), or if you prefer, you can email Ian Lyttle at ian [dot] lyttle [at] se [dot] com (probably safe to use the actual email in the actual email).

Thanks!

**Pull request merged**
